services:
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb
    volumes:
      - database:/var/lib/mysql
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    
  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    build:
    context: ./srcs/nginx
    args:
      CERT_FOLDER: $CERT_FOLDER
      CERTIFICATE: $CERTIFICATE
      kEY: $KEY
      COUNTRY: $COUNTRY
      STATE: $STATE
      LOCALITY: $LOCALITY
      ORGANIZATION: $ORGANIZATION
      UNIT: $UNIT
      COMMON_NAME: $COMMON_NAME
    ports: 
      - "443:443"
    volume:
      - wordpress:/var/www/wordpress
    networks:
      - all
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress
      
volumes:

  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database

  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files

networks:
  all:
    driver: bridge